#!/bin/bash

## Description: Get and set the WordPress environment types
## Usage: wp-env-type [type]
## Example: "ddev wp-env-type debug" or "ddev wp-env-type" (https://make.wordpress.org/core/2020/08/27/wordpress-environment-types/)
## ProjectTypes: wordpress

if [ -f "/var/www/html/wp-config.php" ]; then
    case $1 in
        production|staging|development|local)      
            wp config set WP_ENVIRONMENT_TYPE $1
            ;;
        *)
            echo "The value of WP_ENVIRONMENT_TYPE is: "; wp config get WP_ENVIRONMENT_TYPE
            ;;
    esac
else
    echo "WordPress is probably not installed. That's why I'd rather quit now."
    exit 1
fi
